# Generated by Django 5.1.6 on 2025-03-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
